title: "openlane-guide" 
description: "openlane-guide"
lang: ja

url: "https://samizo-aitl.github.io"
baseurl: "/openlane-guide"

# テーマは使わない（完全自作）
theme: null
remote_theme: null

# Markdown / Math
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

# 明示的に公開対象を指定
include:
  - assets
  - _layouts
  - _includes

exclude: []
